server:
  port: 8080

spring:
  application:
    name: aagam
  datasource:
    url: jdbc:mysql://localhost:3306/aagam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: atri
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,httptrace
  endpoint:
    health:
      show-details: always
